
language: python
python:
    - "3.6"

env:
    global:
        - SPARK_HOME=/tmp/spark-2.2.0-bin-hadoop2.7
        - secure:  "sQ3+ELlqK6QdAyH1J4HmtxtKKA4Bk4Hcu+Hmo3Tslynh0j55+CV2j73jYwch24yGHKheoSA8RVdoP52MoguWo+2ciKIZiumShRNKx1zsYWoJFSb0JlGHogauWNuKEPEzHz8nrw3Z8btyNVFGC25WxXJ490lZ43QnMQ2TpGWNtx7Un/LuZhFFEDJQcl4X5SClGbv8beImKGRHh/DNpjzaw9/EZhY+xT3p820dvm2jdDlKtz8IOE2H3XeAM7raQplio1l5zfSjDIhOy+ESo3uGol4PHjhVe2oIpPnBf0BrYIDYff4L9/TUmgWa875hy8CX4E1T6w89YHFVTI4gRa9YEVpgFRe8AW4XI3CdCTmYMcyf1R2xAW7xOXCBHJegx/kLO2yT3BBScjZc7QhRnXk4587P8t3ciOsPEU0U1LzKgftyvc+aJzBFal3IRaRLI1Ji03PY/JESmjKMz3eVT9bLb8aHdaGF+qH9AC8v1Zcek34ip98DP0qww1QK4AQ/F0IC4TFe6KAs1df8ub8x7hWd7rPEVBThKPatPyQ31oXYHlkuPbXI7/6QWylPBtRwX51Wp9QzgDevCOoIR7JnxYQynAf45TZmlAISBcwo1N2KoxaXOAtytxWFzcaXAoYTwvXTlR0CkhXeusyoabQrCYsmL2at0ZCfmHVVHc69IeGSYxQ="
        - secure: "rbzcB7761B5wFTsWRQb7lQYKIift2X6XlLBgDCd0iQII+PO8stP8px4l0rb/ELfVdqBv9s4aoAinXlLdp99hjhrrtYhbuk5imc4oNy0WpbMAEqccB47zUhy8efCAd9VGNLj7LX+TBef0DShpRVcFS62m5Oa0Z835vmKQhXsRf8ILiczEbfD7FKx3bLc2WtMOz8A1hZBrnXST5q9PAvvpmRuEC5SPxbAvmvlqbGGJ08c0HnfeeKRcvPwpMq/MuL8H0HU8EKpOE95QOV5Qe7su/YQYcQTyMFWINJ5SrWN5HlA2LUxeOE6ijDllxdX8JKKo3e8cZdbJFQhff1h0jl/m+xhMoAFbnxfyzUjGtFg6uAiuTtLw4FvTBFKXMME2LRUothEhMTh6KknZZDlqxFyoAXfWwCN7dsjY/nT7TJa/BZh+024e5T6wTm8srRGMpVgu+r0gjB9dG2s0lMIzOj6K77PIxJDx45m5Cw7HwZPZwe1HIWyOoct7Er3pNKGFvt9AXLpj85sp6FWzzJC4cGJ0SV5UhWI75NujpVO8jKn1gOuYBdSrP6y9ytJiQIvh4YDSpF19v7qsYeRIg64yH5x16OnY03aUxEQytASOrAng6BeUVanJPa6EwSJRfNl0xWcmaj+MkyQPqapnKuiiqnLlJeDTH8pnr/GUMpSDeFD6sQg="
        - AIRBRAKE_ENVIRONMENT=development

before_install:
    - chmod +x install-spark-2-2.sh
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install findspark
    - pip install seaborn
    - pip install matplotlib
    - pip install ipython
    - pip install pytest-spark
    - pip install spark-df-profiling-optimus
    - pip install pixiedust-optimus

install:
    - ./install-spark-2-2.sh
    - "pip install -r requirements-test.txt"

addons:
  sonarcloud:
    organization: "ironmussa"
    token:
      secure: "lF6xKDkh57MC+dlkiovdBA2MPPt7wcH4ANqc07Xyiqnwr898Gy2hwURvqroqm2EFcDQUwd4VJC4+idEjXADP1ugM+FjtHdr4wqDZXXGbO7wCrTdVTYHmPm+0cvmNXyl/JkshWmwktilhYK8Lw+WO3e9NM/WdUKCtY3s1PI2/aFli5XfurySph7jl6wWch/mUO0gBOhKJja5yDc6LPSSx0W+Eczk5FRMOqEAF5OOWFr4baZCLiCr4Fq46JJsNO71Jb/LVGarpo2KUsWOoBYtBldgCcoGK2PQdOSqAG+ObxgFEvZpmi1IeGDDsO26N6vLBfrDmTwS+xB7NEUjrUVpeDLhN9RpoBFyAqOI42UDxbj0lczEIQeze5AHLbxKjmokGxWa8WeGaIzRJqmjTn/ekNLoXpFMLZY4RFxkmAf5puCoOdbIXb8VfhbO/JAiT6O51Xb4zVxDmUETiwYPMKWlZ3ug+Xal/nTTmcZWKBl7GAO1cZAUHg8/EI/SE5SrXxrieo0rmXZ8vZdhp8BFIz0aO5evXnObiwHqeXq5xV8xqhrnSi/mR8uTnqi8Rc/0EaQTMdBTSkBFyCjVDidhwBxGemjSfxXERiEFopumSrvN0K+dS2NJV8JQmgyGPovow4cFYUHE1IiQ5KvRBIT+cSwuvvbjC/i7EL11mCZbtk1pBaKo="
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
    
script:
    - py.test -v
    - sonar-scanner

deploy:
  provider: pypi
  user: "faviovazquez"
  password:
    secure: "YAVFUdSdO0CM4Y92uHjie8StctPb0bh2YZ8HXxMRG6U1hAqZHuh+7FT1yUlH8gqThysm07n7XfoYnfMXGI5sj3xxuiTYrA1eHJwHPn8geRmGMa9j/sWcg8lGk3o48k/Ur//DrKHFvX692ZbCc659zake/IU8MgnOV3NpVnN3lC8OEhNq5D+0WNt0cWYgEIjzUfJUnKJQ9ZF92lyTe0pnn3DwDL6jjaqSVSBYNTgAsf0Rc76BT2fXs8RDiD+zsvxjEoX7U5nazPMtzFUITW1dXzlvpJLXkkVd8HUF4lxBjE2Wm6SFj67sz9VZ+HEGPMzJEFpR3mHHluN00Qw5Nr9RvRG1ivFGPb309LN19jAmuOthPrq65/GSNtlV2bi8ndXCrlu01H2HBXaiF1cXgc++ThIm6mkViQMdGTo+xTvc6UPHTBTH94cIAZCix361yNbiAx4N2XhXGjq+1qMs2Z/qb9mNWw4NVTIsruFSQQXD5iSEwBQltLHo/JEkuR3MgoExyEcQmG7mf/ukgh8Wcenv4UjFOBuEdZgcj4zXn2jva4PaRUGkoJkQsji27Wd8BQjAyNGoz0wnOp7gaLDIOqG/6v+RCNVOfQNBuI1D9OPSzWYSD95/2gLayc+mSgr7hrlgsVsScmz4MdhS4E/0ay3zdQz7MoyMJlHfadfICaJxQI4="
    on:
      tags: true
      branch: develop

notifications:
  email: false
  slack:
    secure: "LsrLufpz5yLaouTM0V5uDy8u3QhBeN42PaT2pbkfUNQysSyF6/9LNMbwlhkUjf4IAEpKkFvRgGg5IlEF8XtXf5xaAJQXTG9Y92EUU62Nv5kj47iXHd7O75gvwgSjqs6a60F1vG0nWkgCJZjmr02eeAnwM25b6bxSM3GgnDyq3e+NJAza5vkkvCgUcwxL5ZtoY/za9xdE16yfgTkAhqRwR2ajzxFBsNOgSN04pgF9K69WM2vopY65N/vBDCQAnQPwlglXxCsf6caKqzXL1ohpQCeqOD5nMbyN1LlF51/UPSrQfMYiKt8ogI61+WYFB0jiueX/trCbd5lBvf8dkd9v6mH8o33sPo6f5ddsrwH9IkRrNsKQtxw/AkekteVmXZ5ym61yISfuRuuqVcy6yYqLrSh+oR9/+NWhZhBfxL03Lb6uotfa/v5s36INW+puyX+Ef22voSjeA9HgUhUMUoKiQkkSxMO1Pr2boOPDDsnyzgiUnKPt/S/PnGv03DYQxdLqdtf6b1jmFNaVSZEwINntmZxtxTArsCaehNKMCA9Amz1MHderkPDHLPGHDmzKq2pv5HCW3a2cH/ic4CudHTtC79JR0Ag85lrEAKXVaijV7FDQIcrFO3Tyug6yMd3CGAhmUIBUZHkcUZ1xNiBkv80HwTIrG3RWqklbdoEJmDYSnFQ="
  
after_success:
    - coveralls
