
language: python
python:
    - "3.5"

env:
    global:
        - SPARK_HOME=/tmp/spark-1.6.0-bin-hadoop2.6

install:
    - ./install-spark-1-6.sh
    - "pip install -r requirements-test.txt"
    
notifications:
  email: false
