
language: python
python:
    - "3.5"

env:
    global:
        - SPARK_HOME=/tmp/spark-2.2.0-bin-hadoop2.7
        - secure:  "sQ3+ELlqK6QdAyH1J4HmtxtKKA4Bk4Hcu+Hmo3Tslynh0j55+CV2j73jYwch24yGHKheoSA8RVdoP52MoguWo+2ciKIZiumShRNKx1zsYWoJFSb0JlGHogauWNuKEPEzHz8nrw3Z8btyNVFGC25WxXJ490lZ43QnMQ2TpGWNtx7Un/LuZhFFEDJQcl4X5SClGbv8beImKGRHh/DNpjzaw9/EZhY+xT3p820dvm2jdDlKtz8IOE2H3XeAM7raQplio1l5zfSjDIhOy+ESo3uGol4PHjhVe2oIpPnBf0BrYIDYff4L9/TUmgWa875hy8CX4E1T6w89YHFVTI4gRa9YEVpgFRe8AW4XI3CdCTmYMcyf1R2xAW7xOXCBHJegx/kLO2yT3BBScjZc7QhRnXk4587P8t3ciOsPEU0U1LzKgftyvc+aJzBFal3IRaRLI1Ji03PY/JESmjKMz3eVT9bLb8aHdaGF+qH9AC8v1Zcek34ip98DP0qww1QK4AQ/F0IC4TFe6KAs1df8ub8x7hWd7rPEVBThKPatPyQ31oXYHlkuPbXI7/6QWylPBtRwX51Wp9QzgDevCOoIR7JnxYQynAf45TZmlAISBcwo1N2KoxaXOAtytxWFzcaXAoYTwvXTlR0CkhXeusyoabQrCYsmL2at0ZCfmHVVHc69IeGSYxQ="
        - secure: "rbzcB7761B5wFTsWRQb7lQYKIift2X6XlLBgDCd0iQII+PO8stP8px4l0rb/ELfVdqBv9s4aoAinXlLdp99hjhrrtYhbuk5imc4oNy0WpbMAEqccB47zUhy8efCAd9VGNLj7LX+TBef0DShpRVcFS62m5Oa0Z835vmKQhXsRf8ILiczEbfD7FKx3bLc2WtMOz8A1hZBrnXST5q9PAvvpmRuEC5SPxbAvmvlqbGGJ08c0HnfeeKRcvPwpMq/MuL8H0HU8EKpOE95QOV5Qe7su/YQYcQTyMFWINJ5SrWN5HlA2LUxeOE6ijDllxdX8JKKo3e8cZdbJFQhff1h0jl/m+xhMoAFbnxfyzUjGtFg6uAiuTtLw4FvTBFKXMME2LRUothEhMTh6KknZZDlqxFyoAXfWwCN7dsjY/nT7TJa/BZh+024e5T6wTm8srRGMpVgu+r0gjB9dG2s0lMIzOj6K77PIxJDx45m5Cw7HwZPZwe1HIWyOoct7Er3pNKGFvt9AXLpj85sp6FWzzJC4cGJ0SV5UhWI75NujpVO8jKn1gOuYBdSrP6y9ytJiQIvh4YDSpF19v7qsYeRIg64yH5x16OnY03aUxEQytASOrAng6BeUVanJPa6EwSJRfNl0xWcmaj+MkyQPqapnKuiiqnLlJeDTH8pnr/GUMpSDeFD6sQg="
        - secure: "kZwnCS0XIDrg0Xre/LqyeDMoJMAMy00KW/rMtslTgFAknjylAUGOY8cCVlEFcOM+lmeCT3cDaiV+J+j5+rYk4LBKhU/n1h4G+Wj6KQdamTPysmSj6CDV0UlMh2vWIA/2qthB+wfOkA7fMl/YFNEc3wrmYKIQkPboSfEbBIyz3K8tZHSn0tKJ5iZlw269OSJdecRJ0lqPBXuY5IMw1wW9IroL2toH+bg55wFR9H0mYo46fBWfLjY1fHwKAtMI2epFxrIlhYejd1fRWyQY4qC8B29P5MgjuCya7OGVYl92M5Ldpl1p91+f2IIbpljxepBha7KKTSSONbOvGWuW9vGR2x86zN2yEBwhKEHZ/Yjoz9kuE9e910I/2YAH+dhwN+ZZKj457dPc4HMtXkXucPyppJoy9jwQIz4ZQbBOxrHgd+YV4gPm9x3P5Jjdic4d7LoYVzVRnGjbsxK1Y8H/oxzN54Jtoge6Oq8ZorDu+poALVhN/qtoXDtb+RGliAqIS9oUceeKMYDxmSPYToNBXAREGnEy5dO+vWUCrfmBOcUDRnUndfzWyx+xfOKiqo2lzz4qNihdwCad6nPzi+3bYUzHOFDrGHJYkQsF1Vj8TGbPXpuKcyRvQsgIn0JetHRifEOjArMM7xkvXYGLjdu7y1PrAj2kcoHPkkz7CpcQgBNvDkc="

before_install:
    - chmod +x install-spark-2-2.sh
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install findspark
    - pip install seaborn
    - pip install matplotlib
    - pip install ipython
    - pip install pytest-spark
    - pip install spark-df-profiling-optimus
    - pip install pixiedust-optimus
    - pip install airbrake
    
install:
    - ./install-spark-2-2.sh
    - "pip install -r requirements-test.txt"

addons:
  sonarcloud:
    organization: "ironmussa"
    token:
      secure: "lF6xKDkh57MC+dlkiovdBA2MPPt7wcH4ANqc07Xyiqnwr898Gy2hwURvqroqm2EFcDQUwd4VJC4+idEjXADP1ugM+FjtHdr4wqDZXXGbO7wCrTdVTYHmPm+0cvmNXyl/JkshWmwktilhYK8Lw+WO3e9NM/WdUKCtY3s1PI2/aFli5XfurySph7jl6wWch/mUO0gBOhKJja5yDc6LPSSx0W+Eczk5FRMOqEAF5OOWFr4baZCLiCr4Fq46JJsNO71Jb/LVGarpo2KUsWOoBYtBldgCcoGK2PQdOSqAG+ObxgFEvZpmi1IeGDDsO26N6vLBfrDmTwS+xB7NEUjrUVpeDLhN9RpoBFyAqOI42UDxbj0lczEIQeze5AHLbxKjmokGxWa8WeGaIzRJqmjTn/ekNLoXpFMLZY4RFxkmAf5puCoOdbIXb8VfhbO/JAiT6O51Xb4zVxDmUETiwYPMKWlZ3ug+Xal/nTTmcZWKBl7GAO1cZAUHg8/EI/SE5SrXxrieo0rmXZ8vZdhp8BFIz0aO5evXnObiwHqeXq5xV8xqhrnSi/mR8uTnqi8Rc/0EaQTMdBTSkBFyCjVDidhwBxGemjSfxXERiEFopumSrvN0K+dS2NJV8JQmgyGPovow4cFYUHE1IiQ5KvRBIT+cSwuvvbjC/i7EL11mCZbtk1pBaKo="
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
    
script:
    - py.test
    - sonar-scanner

deploy:
  provider: pypi
  user: "faviovazquez"
  password:
    secure: "YAVFUdSdO0CM4Y92uHjie8StctPb0bh2YZ8HXxMRG6U1hAqZHuh+7FT1yUlH8gqThysm07n7XfoYnfMXGI5sj3xxuiTYrA1eHJwHPn8geRmGMa9j/sWcg8lGk3o48k/Ur//DrKHFvX692ZbCc659zake/IU8MgnOV3NpVnN3lC8OEhNq5D+0WNt0cWYgEIjzUfJUnKJQ9ZF92lyTe0pnn3DwDL6jjaqSVSBYNTgAsf0Rc76BT2fXs8RDiD+zsvxjEoX7U5nazPMtzFUITW1dXzlvpJLXkkVd8HUF4lxBjE2Wm6SFj67sz9VZ+HEGPMzJEFpR3mHHluN00Qw5Nr9RvRG1ivFGPb309LN19jAmuOthPrq65/GSNtlV2bi8ndXCrlu01H2HBXaiF1cXgc++ThIm6mkViQMdGTo+xTvc6UPHTBTH94cIAZCix361yNbiAx4N2XhXGjq+1qMs2Z/qb9mNWw4NVTIsruFSQQXD5iSEwBQltLHo/JEkuR3MgoExyEcQmG7mf/ukgh8Wcenv4UjFOBuEdZgcj4zXn2jva4PaRUGkoJkQsji27Wd8BQjAyNGoz0wnOp7gaLDIOqG/6v+RCNVOfQNBuI1D9OPSzWYSD95/2gLayc+mSgr7hrlgsVsScmz4MdhS4E/0ay3zdQz7MoyMJlHfadfICaJxQI4="
    on:
      tags: true
      branch: develop

notifications:
  email: false
  
after_success:
    - coveralls
