
language: python
python:
    - "3.6"
    - "3.6-dev" # 3.6 development branch

env:
    global:
        - SPARK_HOME=/tmp/spark-2.2.1-bin-hadoop2.7

before_install:
    - chmod +x install-spark-2-2.sh
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install findspark
    - pip install seaborn
    - pip install matplotlib
    - pip install ipython
    - pip install spark-df-profiling-optimus
    - pip install pixiedust-optimus

install:
    - ./install-spark-2-2.sh
    - "pip install -r requirements-test.txt"

addons:
  sonarcloud:
    organization: "ironmussa"
    token:
      secure: "lF6xKDkh57MC+dlkiovdBA2MPPt7wcH4ANqc07Xyiqnwr898Gy2hwURvqroqm2EFcDQUwd4VJC4+idEjXADP1ugM+FjtHdr4wqDZXXGbO7wCrTdVTYHmPm+0cvmNXyl/JkshWmwktilhYK8Lw+WO3e9NM/WdUKCtY3s1PI2/aFli5XfurySph7jl6wWch/mUO0gBOhKJja5yDc6LPSSx0W+Eczk5FRMOqEAF5OOWFr4baZCLiCr4Fq46JJsNO71Jb/LVGarpo2KUsWOoBYtBldgCcoGK2PQdOSqAG+ObxgFEvZpmi1IeGDDsO26N6vLBfrDmTwS+xB7NEUjrUVpeDLhN9RpoBFyAqOI42UDxbj0lczEIQeze5AHLbxKjmokGxWa8WeGaIzRJqmjTn/ekNLoXpFMLZY4RFxkmAf5puCoOdbIXb8VfhbO/JAiT6O51Xb4zVxDmUETiwYPMKWlZ3ug+Xal/nTTmcZWKBl7GAO1cZAUHg8/EI/SE5SrXxrieo0rmXZ8vZdhp8BFIz0aO5evXnObiwHqeXq5xV8xqhrnSi/mR8uTnqi8Rc/0EaQTMdBTSkBFyCjVDidhwBxGemjSfxXERiEFopumSrvN0K+dS2NJV8JQmgyGPovow4cFYUHE1IiQ5KvRBIT+cSwuvvbjC/i7EL11mCZbtk1pBaKo="
    github_token:
      secure: "L0q/F9syTHCio1/DSvmEy95N04lg9UgpmvRUgj2XJqCAIRpojIEdRE74mXlgfztgMEQ4Im9MJSXNN97ADzgQTvt/Cm9HM6op2xhUWp1F+zmkkONsEd95yO0ojHgx9LxGV7S8NoryQTBkGHQ9LzgDvnUoaN1XlThlDv+KyCAyRcQ95e4MttjE2l+vvtOCRjrxJWAIGUCLylJapzH2QHagUZE01MqHye80QzBqq4bajSK5FI38tsTgAW+ODczC4q+3ea2zNyup9uAdDgElygSP48VT3TWMb0CR8IZ1S+tEJLDuOUueJ89493vMaW6GBoXL/1vEWT7yJpfSb53qB2aH91RVH3utGpQC9/FS66gP68+mViLTbNrXfO4mhLxF1Ehi+qBa+u+N4FfkyMuOarhUKbWgS+pldMtFKBb5ah6DyiJB+eUMPXSZfTqlHysjg15w1xsf6VlFtCAVlcp4XDYRBaq3vv+WUlnpGcl7xBe0DGwH9zgSxH+RX84RCVVFTWmgTRySRSVvrjdCRru61YRVLiS6aGDqS3Yxt3dIjOuANY5TVm/XBb3xWTUSD4CieGUhCa1iEgG834LWuvjHVQRb5VJLVzauKIiWdPAmu/ghQJMe2cQUtEwqFdMcbu5WCagdcVjMzYqDXKmfiLghmfh5rGYjFRiH1jNl6xO7z4KWTIo="
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
    
script:
    - py.test -v
    - if [ "$TRAVIS_BRANCH" = "develop" ]; then sonar-scanner; fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then sonar-scanner; fi

deploy:
  provider: pypi
  user: "faviovazquez"
  password:
    secure: "YAVFUdSdO0CM4Y92uHjie8StctPb0bh2YZ8HXxMRG6U1hAqZHuh+7FT1yUlH8gqThysm07n7XfoYnfMXGI5sj3xxuiTYrA1eHJwHPn8geRmGMa9j/sWcg8lGk3o48k/Ur//DrKHFvX692ZbCc659zake/IU8MgnOV3NpVnN3lC8OEhNq5D+0WNt0cWYgEIjzUfJUnKJQ9ZF92lyTe0pnn3DwDL6jjaqSVSBYNTgAsf0Rc76BT2fXs8RDiD+zsvxjEoX7U5nazPMtzFUITW1dXzlvpJLXkkVd8HUF4lxBjE2Wm6SFj67sz9VZ+HEGPMzJEFpR3mHHluN00Qw5Nr9RvRG1ivFGPb309LN19jAmuOthPrq65/GSNtlV2bi8ndXCrlu01H2HBXaiF1cXgc++ThIm6mkViQMdGTo+xTvc6UPHTBTH94cIAZCix361yNbiAx4N2XhXGjq+1qMs2Z/qb9mNWw4NVTIsruFSQQXD5iSEwBQltLHo/JEkuR3MgoExyEcQmG7mf/ukgh8Wcenv4UjFOBuEdZgcj4zXn2jva4PaRUGkoJkQsji27Wd8BQjAyNGoz0wnOp7gaLDIOqG/6v+RCNVOfQNBuI1D9OPSzWYSD95/2gLayc+mSgr7hrlgsVsScmz4MdhS4E/0ay3zdQz7MoyMJlHfadfICaJxQI4="
    on:
      tags: true
      branch: develop

notifications:
  email: false
  slack:
    secure: "LsrLufpz5yLaouTM0V5uDy8u3QhBeN42PaT2pbkfUNQysSyF6/9LNMbwlhkUjf4IAEpKkFvRgGg5IlEF8XtXf5xaAJQXTG9Y92EUU62Nv5kj47iXHd7O75gvwgSjqs6a60F1vG0nWkgCJZjmr02eeAnwM25b6bxSM3GgnDyq3e+NJAza5vkkvCgUcwxL5ZtoY/za9xdE16yfgTkAhqRwR2ajzxFBsNOgSN04pgF9K69WM2vopY65N/vBDCQAnQPwlglXxCsf6caKqzXL1ohpQCeqOD5nMbyN1LlF51/UPSrQfMYiKt8ogI61+WYFB0jiueX/trCbd5lBvf8dkd9v6mH8o33sPo6f5ddsrwH9IkRrNsKQtxw/AkekteVmXZ5ym61yISfuRuuqVcy6yYqLrSh+oR9/+NWhZhBfxL03Lb6uotfa/v5s36INW+puyX+Ef22voSjeA9HgUhUMUoKiQkkSxMO1Pr2boOPDDsnyzgiUnKPt/S/PnGv03DYQxdLqdtf6b1jmFNaVSZEwINntmZxtxTArsCaehNKMCA9Amz1MHderkPDHLPGHDmzKq2pv5HCW3a2cH/ic4CudHTtC79JR0Ag85lrEAKXVaijV7FDQIcrFO3Tyug6yMd3CGAhmUIBUZHkcUZ1xNiBkv80HwTIrG3RWqklbdoEJmDYSnFQ="
  
after_success:
    - coveralls
