{% set version = "3.0.0" %}

package:
  name: optimus
  version: {{ version }}

source:
  git_url: https://github.com/ironmussa/Optimus
  git_rev: develop-3.0
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - simplejson            3.16.0        no  Could be sustitude by json
    - fastnumbers           3.0.0         no
    - multipledispatch      0.6.0         no
    - matplotlib            3.0.3
    - seaborn               0.9.0
    - setuptools            41.6.0
    - Jinja2                2.10.1
    - humanize              0.5.1         no
    - pandas                1.0.5
    - statsmodels           0.10.1
    - glom                  19.10.0       no
    - nltk                  3.4.5

about:
  home: https://github.com/ironmussa/optimuspyspark
  license: MIT
  summary: 'Agile Data Science Workflows made easy with Pyspark, Dask, cuDF, and dask-cuDF'
  description: Agile Data Science Workflows made easy with Pyspark, Dask, cuDF, and dask-cuDF
  dev_url: https://github.com/ironmussa/Optimus
  doc_url: https://pypi.python.org/pypi/optimuspyspark
  doc_source_url: https://github.com/ironmussa/optimuspyspark/blob/master/README.rst