{% set version = "3.0.0" %}

package:
  name: optimuspyspark
  version: {{ version }}

source:
  git_url: https://github.com/ilanschnell/bsdiff4.git
  git_rev: 1.1.4
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - simplejson==3.16.0
    - cryptography==2.7
    - imgkit==1.0.1
    - packaging==19.1
    - requests==2.20.0
    - tqdm==4.28.1
    - fastnumbers==2.2.1
    - multipledispatch==0.6.0
    - numpy==1.17.2
    - matplotlib==3.0.3
    - pyspark==2.4.1
    - findspark==1.3.0
    - seaborn==0.9.0
    - deprecated==1.2.5
    - setuptools==41.6.0
    - pyarrow==0.13.0
    - Jinja2==2.10.1
    - tensorflow==1.13.1
    - keras==2.2.4
    - pygments>=2.2.0
    - ipython==7.5.0
    - ratelimit==2.2.1
    - humanize==0.5.1
    - h2o-pysparkling-2.4==2.4.13
    - psutil==5.6.3
    - backoff==1.8.0
    - kombu==4.6.1
    - pandas==0.24.2
    - ordered-set==3.1.1
    - deepdiff==4.0.6
    - statsmodels==0.10.1
    - glom==19.10.0
    - singleton-decorator==1.0.0
    - nltk==3.4.5
    - fastavro==0.22.7
    - dask[complete]==2.9.2
    - dask-ml[complete]==1.2.0
    -
test:
  imports:
    - imgkit==1.0.1
    - simplejson==3.16.0
    - mock==3.0.5
    - nose==1.3.7
    - pylint==2.3.1
    - fastnumbers==2.2.1
    - multipledispatch==0.6.0
    - python_dateutil==2.7.5
    - numpy==1.17.2
    - matplotlib==3.0.3
    - pyspark==2.4.1
    - pytest==4.6.2
    - findspark==1.3.0
    - nose==1.3.7
    - seaborn==0.9.0
    - deprecated==1.2.5
    - setuptools==41.6.0
    - pyarrow==0.13.0
    - tabulate==0.8.2
    - Jinja2==2.10.1
    - tensorflow==1.13.1
    - keras==2.2.4
    - pillow==6.2.0
    - pygments>=2.2.0
    - six>=1.10.0
    - h5py>=2.7.0
    - flask==1.0.2
    - ipython==7.5.0
    - humanize==0.5.1
    - psutil==5.6.3
    - pytest-cov==2.7.1
    - backoff==1.8.0
    - h2o_pysparkling_2.4==2.4.12
    - ratelimit==2.2.1
    - tqdm==4.28.1
    - kombu==4.6.1
    - packaging==19.1
    - ordered-set==3.1.1
    - deepdiff==4.0.6
    - papermill==1.0.1
    - cryptography==2.7
    - statsmodels==0.10.1
    - glom==19.10.0
    - singleton-decorator==1.0.0
    - nltk==3.4.5

about:
  home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/shibukawa/imagesize_py
  doc_url: https://pypi.python.org/pypi/imagesize
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst